name: BattlePass
version: '8.0'
main: com.Lino.battlePass.BattlePass
api-version: '1.21'
author: Lino
website: https://www.spigotmc.org/resources/battlepass.125992/
softdepend: [PlaceholderAPI, MythicMobs]

libraries:
  - com.zaxxer:HikariCP:5.1.0
  - com.mysql:mysql-connector-j:8.3.0
  - org.slf4j:slf4j-api:2.0.9
  - org.slf4j:slf4j-simple:2.0.9

commands:
  battlepass:
    description: Open the BattlePass GUI or manage battle pass system
    usage: /battlepass [help|reload|addpremium|removepremium|addxp|removexp|addcoins|removecoins] [player] [amount]
    aliases: [bp, pass]
    permission: battlepass.use
    permission-message: You don't have permission to use this command!

permissions:
  battlepass.use:
    description: Allows use of /battlepass command
    default: true
  battlepass.admin:
    description: Access to admin commands (reload, addpremium, removepremium)
    default: op