name: BattlePass
version: '1.1'
main: com.Lino.battlePass.BattlePass
api-version: '1.21'
author: Lino

commands:
  battlepass:
    description: Open the BattlePass GUI or manage premium passes
    usage: /battlepass [reload|addpremium|removepremium] [player]
    aliases: [bp, pass]
    permission: battlepass.use
    permission-message: You don't have permission to use this command!

permissions:
  battlepass.use:
    description: Allows use of /battlepass command
    default: true
  battlepass.admin:
    description: Access to admin commands (reload, addpremium, removepremium)
    default: op