name: BattlePass
version: '8.1'
main: com.Lino.battlePass.BattlePass
api-version: '1.16'
author: Lino
website: https://www.spigotmc.org/resources/battlepass.125992/
softdepend: [PlaceholderAPI, MythicMobs]

commands:
  battlepass:
    description: Открыть GUI BattlePass или управлять системой боевого пропуска
    usage: /battlepass [help|reload|addpremium|removepremium|addxp|removexp|addcoins|removecoins] [игрок] [кол-во]
    aliases: [bp, pass]
    permission: battlepass.use
    permission-message: У вас нет прав на использование этой команды!

permissions:
  battlepass.use:
    description: Разрешает использовать команду /battlepass
    default: true
  battlepass.admin:
    description: Доступ к админ-командам (reload, addpremium, removepremium)
    default: op
